safe: true
lsi: false
pygments: true
name: The Hackerati
description: website for The Hackerati
url: http://thehackerati.com

# Settings for sharing 
# Sharing is for things like tweet, plusone, hn upvotes, like, linkedin
# Add a tweet button    => provider : tweet
# Add a like button     => provider : like (you also need a facebook appid)
# Add a plus one button   => provider : plusone
# Add a HN button     => provider : hn
# Add them all (i.e. hn + tweet + plusone + like) => provider : all
# Set 'provider' to the sharing provider you want to use.
# Set 'provider' to false to turn sharing off globally.
#
sharing :
  provider : all
  twitter :
    size :
    via :
    count :
  facebook :
    appid : 398199466992474
    layout : button_count
    font :
    faces : false
    width : 90
  googleplus :
    size : medium
    width :
    annotation : bubble
  linkedin :
    counter : right

# Settings for comments helper
# Set 'provider' to the comment provider you want to use.
# Set 'provider' to false to turn commenting off globally.
#
#  comments :
#    provider : disqus
#    disqus :
#      short_name : jekyllbootstrap
#    livefyre :
#      site_id : 123
#    intensedebate :
#      account : 123abc
#    facebook :
#      appid : 123
#      num_posts: 5
#      width: 580
#      colorscheme: light 
#
#
#  # Settings for analytics helper
#  # Set 'provider' to the analytics provider you want to use.
#  # Set 'provider' to false to turn analytics off globally.
#  #        
#  analytics :
#    provider : google 
#    google : 
#        tracking_id : 'UA-123-12'
#    mixpanel :
#        token : '_MIXPANEL_TOKEN_'
#
